version: "3.9"

services:
  springboot:
    container_name: springboot
    image: seungheon123/vincent:latest
    networks:
      - my_network
    environment:
      - TZ=Asia/Seoul
      - REDIS_HOST=${PROD_REDIS_HOST}
      - REDIS_PORT=${PROD_REDIS_PORT}
      - DB_URL=${PROD_DB_URL}
      - DB_USERNAME=${PROD_DB_USERNAME}
      - DB_PASS=${PROD_DB_PASS}
      - JWT_TOKEN_SECRET=${PROD_JWT_TOKEN_SECRET}
      - BUCKET_NAME=${PROD_BUCKET_NAME}
      - BUCKET_ACCESS_KEY=${PROD_BUCKET_ACCESS_KEY}
      - BUCKET_SECRET_KEY=${PROD_BUCKET_SECRET_KEY}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - my_network
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

networks:
  my_network:
    driver: bridge
