version: "3.9"

services:
  springboot:
    container_name: springboot
    image: seungheon123/vincent:latest
    networks:
      - my_network
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASS=${DB_PASS}
      - JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}
      - BUCKET_NAME=${BUCKET_NAME}
      - BUCKET_ACCESS_KEY=${BUCKET_ACCESS_KEY}
      - BUCKET_SECRET_KEY=${BUCKET_SECRET_KEY}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - my_network
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus 설정 파일 마운트
#    ports:
#      - "9090:9090"
#    networks:
#      - my_network
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    networks:
#      - my_network
#    depends_on:
#      - prometheus
networks:
  my_network:
    driver: bridge
