FROM openjdk:17
ARG DB_URL
ARG DB_USERNAME
ARG DB_PASS
ARG JWT_TOKEN_SECRET
ARG BUCKET_NAME
ARG BUCKET_ACCESS_KEY
ARG BUCKET_SECRET_KEY
ARG REDIS_HOST
ARG REDIS_PORT
ARG JAR_FILE=build/libs/*.jar
ARG  SPRING_PROFILE=dev

COPY ${JAR_FILE} app.jar

ENV DB_URL=${DB_URL}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASS=${DB_PASS}
ENV JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}
ENV BUCKET_NAME=${BUCKET_NAME}
ENV BUCKET_ACCESS_KEY=${BUCKET_ACCESS_KEY}
ENV BUCKET_SECRET_KEY=${BUCKET_SECRET_KEY}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}

EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]
