version: "3.9"

services:
  springboot:
    container_name: springboot
    image: seungheon123/vincent:latest
    networks:
      - my_network
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT={REDIS_PORT}
      # .env 파일에서 가져온 환경 변수들을 여기에 추가
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASS=${DB_PASS}
      - JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}
      - BUCKET_NAME=${BUCKET_NAME}
      - BUCKET_ACCESS_KEY=${BUCKET_ACCESS_KEY}
      - BUCKET_SECRET_KEY=${BUCKET_SECRET_KEY}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - my_network
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
networks:
  my_network:
    driver: bridge
