spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: Vincent

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  http:
    multipart:
      enabled: true

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - loggers
          - mappings
          - metrics
          - shutdown
          - prometheus
