name: Vincent CI/CD
on:
    push:
        branches:
        - main
        - Ci/63
    pull_request:
        branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew clean build --exclude-task test --warning-mode all

        - name: Cache Gradle package
          uses: actions/cache@v1
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
            restore-keys: ${{ runner.os }}-gradle

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4.0.0
          with:
            context: .
            file: ./Dockerfile
            push: true
            args: |
              DB_URL=${{ secrets.DB_URL }}
              DB_USERNAME=${{ secrets.DB_USERNAME }}
              DB_PASS=${{ secrets.DB_PASS }}
              JWT_TOKEN_SECRET=${{ secrets.JWT_TOKEN_SECRET }}
              BUCKET_NAME=${{ secrets.BUCKET_NAME }}
              BUCKET_ACCESS_KEY=${{ secrets.BUCKET_ACCESS_KEY }}
                BUCKET_SECRET_KEY=${{ secrets.BUCKET_SECRET_KEY }}
            tags: ${{ secrets.DOCKER_USERNAME }}/vincent:latest
